[bash] Fix a whole bunch of shellcheck warnings

diff --git a/Bash/bashrc b/Bash/bashrc
--- a/Bash/bashrc
+++ b/Bash/bashrc
@@ -35,7 +35,7 @@ if [[ "$PS1" ]]; then
     _run_verbose() {
         (
             # Strip visible escape sequences from $PS4; bash prompting works differently from echo.
-            printf "${PS4}" | sed -e 's/\\\[//g' -e 's/\\\]//g'
+            printf "%s" "${PS4}" | sed -e 's/\\\[//g' -e 's/\\\]//g'
             echo "$@"
         ) >&2
         "$@"
@@ -45,8 +45,8 @@ if [[ "$PS1" ]]; then
     PROMPT_DIRTRIM=3
 
     # Git status in prompt using __git_ps1()
-    GIT_PS1_SHOWDIRTYSTATE=1
-    GIT_PS1_SHOWUPSTREAM="git verbose"
+    export GIT_PS1_SHOWDIRTYSTATE=1
+    export GIT_PS1_SHOWUPSTREAM="git verbose"
 
     # Trailing newline warning using cursor column detection
     #
@@ -59,12 +59,13 @@ if [[ "$PS1" ]]; then
             _prompt_newline_warning_enabled=1;
             _cursor_column() {
                 exec < /dev/tty
-                local stty_save=$(stty -g)
+                local stty_save
+                stty_save=$(stty -g)
                 stty raw -echo min 0
                 echo -en "\e[6n" > /dev/tty
                 stty "$stty_save"
                 local curcol
-                read -s -d R curcol
+                read -r -s -d _ curcol
                 curcol="${curcol##*;}"
                 echo -n "$curcol"
             }
@@ -81,12 +82,12 @@ if [[ "$PS1" ]]; then
     _fmt_seconds_elapsed() {
         local n=$1
         local output=""
-        local h=$(($n / 3600))
+        local h=$((n / 3600))
         [[ $h -gt 0 ]] && output+="${h}h"
-        n=$(($n % 3600))
-        local m=$(($n / 60))
+        n=$((n % 3600))
+        local m=$((n / 60))
         [[ $m -gt 0 ]] && output+="${m}m"
-        s=$(($n % 60))
+        s=$((n % 60))
         output+="${s}s"
         echo "${output}"
     }
@@ -101,22 +102,22 @@ if [[ "$PS1" ]]; then
 
         # Colour definitions
         local colour_normal="\[\e[0m\]"
-        local colour_black="\[\e[0;30m\]"
-        local colour_black_bold="\[\e[1;30m\]"
+        # local colour_black="\[\e[0;30m\]"
+        # local colour_black_bold="\[\e[1;30m\]"
         local colour_red="\[\e[0;31m\]"
-        local colour_red_bold="\[\e[1;31m\]"
+        # local colour_red_bold="\[\e[1;31m\]"
         local colour_green="\[\e[0;32m\]"
-        local colour_green_bold="\[\e[1;32m\]"
+        # local colour_green_bold="\[\e[1;32m\]"
         local colour_yellow="\[\e[0;33m\]"
-        local colour_yellow_bold="\[\e[1;33m\]"
+        # local colour_yellow_bold="\[\e[1;33m\]"
         local colour_blue="\[\e[0;34m\]"
-        local colour_blue_bold="\[\e[1;34m\]"
+        # local colour_blue_bold="\[\e[1;34m\]"
         local colour_purple="\[\e[0;35m\]"
-        local colour_purple_bold="\[\e[1;35m\]"
+        # local colour_purple_bold="\[\e[1;35m\]"
         local colour_cyan="\[\e[0;36m\]"
-        local colour_cyan_bold="\[\e[1;36m\]"
-        local colour_white="\[\e[0;37m\]"
-        local colour_white_bold="\[\e[1;37m\]"
+        # local colour_cyan_bold="\[\e[1;36m\]"
+        # local colour_white="\[\e[0;37m\]"
+        # local colour_white_bold="\[\e[1;37m\]"
 
         # Error
         local prompt_err=""
@@ -133,7 +134,7 @@ if [[ "$PS1" ]]; then
         # Time since previous command
         local prompt_timer=""
         if [[ -n "${_timer_start}" ]]; then
-            local seconds_elapsed=$(($SECONDS - $_timer_start))
+            local seconds_elapsed=$((SECONDS - _timer_start))
             if [[ $seconds_elapsed -ge 10 ]]; then
                 seconds_elapsed=$(_fmt_seconds_elapsed ${seconds_elapsed})
                 prompt_timer+="${seconds_elapsed} elapsed"
@@ -156,10 +157,11 @@ if [[ "$PS1" ]]; then
             prompt_umbrella=$(command cat .umbrella)
         else
             local dir="${PWD}"
+            local prefix
             while [[ $dir != '/' ]]; do
                 if [[ -r "${dir}/../.umbrella" ]]; then
-                    local prefix=$(command cat "${dir}/../.umbrella")
-                    project=$(basename $dir)
+                    prefix=$(command cat "${dir}/../.umbrella")
+                    project=$(basename "${dir}")
                     prompt_umbrella="${prefix} ${project,,}"
                     break
                 fi
@@ -203,7 +205,8 @@ if [[ "$PS1" ]]; then
         # Git
         local prompt_git=""
         if declare -F __git_ps1 > /dev/null; then
-            local _git_ps1_output="$(__git_ps1 '%s')"
+            local _git_ps1_output
+            _git_ps1_output="$(__git_ps1 '%s')"
             if [[ -n "${_git_ps1_output}" ]]; then
                 prompt_git="git ${_git_ps1_output}"
             fi
@@ -214,9 +217,9 @@ if [[ "$PS1" ]]; then
         if [[ -n "${VIRTUAL_ENV:-}" ]]; then
             local venv_name
             if [[ "${VIRTUAL_ENV}" == */.direnv/* ]]; then
-                venv_name=$(basename $(dirname $(dirname ${VIRTUAL_ENV})))
+                venv_name="$(basename "$(dirname "$(dirname "${VIRTUAL_ENV}")")")"
             else
-                venv_name=$(basename ${VIRTUAL_ENV})
+                venv_name="$(basename "${VIRTUAL_ENV}")"
             fi
             prompt_venv="venv ${venv_name}"
         fi
@@ -231,12 +234,13 @@ if [[ "$PS1" ]]; then
 
         # Background jobs
         local prompt_jobs=""
-        local n_jobs="$(jobs -p | wc -w)"
-        if [[ ${n_jobs} -ne 0 ]]; then
-            local n_jobs_background="$(jobs -p -r | wc -w)"
-            local n_jobs_suspended="$(jobs -p -s | wc -w)"
+        local n_jobs n_jobs_background n_jobs_suspended
+        n_jobs="$(jobs -p | wc -w)"
+        if [[ ${n_jobs} -gt 0 ]]; then
+            n_jobs_background="$(jobs -p -r | wc -w)"
+            n_jobs_suspended="$(jobs -p -s | wc -w)"
             prompt_jobs=""
-            if [[ $(($n_jobs_background + $n_jobs_suspended)) > 0 ]]; then
+            if [[ $((n_jobs_background + n_jobs_suspended)) -gt 0 ]]; then
                 prompt_jobs="jobs"
             fi
             if [[ ${n_jobs_background} -gt 0 ]]; then
@@ -283,7 +287,7 @@ if [[ "$PS1" ]]; then
     PROMPT_COMMAND=set_prompt_command
 
     # Globbing. This makes both "echo *" (only non-hidden files) and "echo .*"
-    # (only hidden files, ignoring . and ..) works as intended.
+    # (only hidden files, ignoring . and ..) work as intended.
     GLOBIGNORE=".:.."
     shopt -u dotglob  # ... since setting GLOBIGNORE enables dotglob as a side effect :-(
     shopt -s extglob
@@ -296,7 +300,7 @@ if [[ "$PS1" ]]; then
     # Completion
     for file in /usr/share/bash-completion/bash_completion /etc/bash_completion /usr/local/share/bash-completion/bash_completion; do
         if [[ -f "$file" ]]; then
-            source $file
+            source "$file"
             break  # stop after first match
         fi
     done
@@ -324,7 +328,7 @@ if [[ "$PS1" ]]; then
         mkdir --verbose --parents "$1" && cd "$1"
     }
     cdp() {
-        cd $(dirname "$1")
+        cd "$(dirname "$1")"
     }
 
     _print_nyan_cat() {
@@ -365,7 +369,7 @@ if [[ "$PS1" ]]; then
             fi
 
             cmd_corrected="$prefix ${cmd#$prefix}$2"
-            _run_verbose $cmd_corrected "${@:3}"
+            _run_verbose "${cmd_corrected}" "${@:3}"
             return
         done
 
@@ -441,7 +445,7 @@ if [[ "$PS1" ]]; then
     alias lessr='less -R'
     maybe-pager() {
         if [[ -t 1 ]]; then  # stdout is a terminal
-            less -FRX "$@"
+            less -FRX
         else
             command cat
         fi
@@ -469,7 +473,7 @@ if [[ "$PS1" ]]; then
         alias git=hub
     fi
     syntax-highlight() {
-        pygmentize -l "$1" "${@:2}" | maybe-pager
+        pygmentize -l "$@" | maybe-pager
     }
 
     # Multiple python installations via pyenv
@@ -487,15 +491,16 @@ if [[ "$PS1" ]]; then
     alias pyt=py.test
     py-cprofile() {
         if [[ $# -lt 1 ]]; then
-            printf "Error: no Python program specified. Usage:\n\n    ${FUNCNAME} some-program --some-args\n" > /dev/stderr
+            printf "Error: no Python program specified. Usage:\n\n    %s some-program --some-args\n" "${FUNCNAME[0]}" > /dev/stderr
             return
         fi
         local prog="$1"
         shift
         if [[ ! -f "$prog" ]]; then
-            prog=$(which $prog)
+            prog="$(which "$prog")"
         fi
-        local profile_file=$(mktemp 'python-cprofile-XXXXXX.prof')
+        local profile_file
+        profile_file="$(mktemp 'python-cprofile-XXXXXX.prof')"
         python -m cProfile -o "$profile_file" "$prog" "$@"
         echo > /dev/stderr
         printf 'sort cumulative\nstats 30\n' | python -m pstats "$profile_file" 1>&2
@@ -503,10 +508,10 @@ if [[ "$PS1" ]]; then
         echo "Profile stored in ${profile_file}" > /dev/stderr
     }
     py-pdb() {
-        python -m pdb $(which "$1") "${@:2}"
+        python -m pdb "$(which "$1")" "${@:2}"
     }
     py-ipdb() {
-        python -m ipdb $(which "$1") "${@:2}"
+        python -m ipdb "$(which "$1")" "${@:2}"
     }
     pytestf() {
         _run_verbose py.test --tb=short --color=yes --looponfail --verbose --verbose "$@"
@@ -580,13 +585,13 @@ if [[ "$PS1" ]]; then
             set -e
             local updates
             _run_verbose brew update
-            updates="$(brew outdated | grep -v -F -f <(find $(brew --prefix)/Library/PinnedKegs/ -mindepth 1 -maxdepth 1 -type l -printf '%f\n') | xargs --no-run-if-empty brew outdated --verbose || true)"
+            updates="$(brew outdated | grep -v -F -f <(find "$(brew --prefix)"/Library/PinnedKegs/ -mindepth 1 -maxdepth 1 -type "l" -printf '%f\n') | xargs --no-run-if-empty brew outdated --verbose || true)"
             if [[ -n "${updates}" ]]; then
                 echo
                 echo "These packages will be upgraded:"
                 echo "${updates}"
                 echo
-                read -p 'Continue upgrade? [Y/n] ' -n 1 CONFIRM
+                read -r -p 'Continue upgrade? [Y/n] ' -n1 CONFIRM
                 if [[ "${CONFIRM}" =~ ^[Yy]?$ ]]; then
                     _run_verbose brew upgrade
                 fi
@@ -600,7 +605,7 @@ if [[ "$PS1" ]]; then
     if [[ ! -z "$ITERM_PROFILE" && -z "$INSIDE_EMACS" ]]; then
         _ITERM_PROFILE_FILE=~/.config/iterm-profile
         _iterm_profile() {
-            printf "\e]50;SetProfile=$1\a"
+            printf "\e]50;SetProfile=%s\a" "$1"
             echo "$1" >| ${_ITERM_PROFILE_FILE}
         }
         dark() {
@@ -610,7 +615,7 @@ if [[ "$PS1" ]]; then
             _iterm_profile "Light"
         }
         if [[ -e ${_ITERM_PROFILE_FILE} ]]; then
-            _iterm_profile $(cat ${_ITERM_PROFILE_FILE})
+            _iterm_profile "$(cat "${_ITERM_PROFILE_FILE}")"
         fi
     fi
 
@@ -641,7 +646,8 @@ if [[ "$PS1" ]]; then
                         true
                     elif type pygmentize &>/dev/null; then
                         # Try to use pygments/pygmentize for syntax highlighting.
-                        local lexer=$(pygmentize -N "$file")
+                        local lexer
+                        lexer="$(pygmentize -N "$file")"
                         if [[ "${can_peek}" == "yes" && "${lexer}" == "text" ]]; then
                             # Heuristics to improve pygmentize's detection (which
                             # uses file names only); detect a few file types using
@@ -702,7 +708,8 @@ if [[ "$PS1" ]]; then
 
     # Readable $PATH (or similar variables)
     echopath() {
-        echo "${1:-$PATH}" | sed -e 's/:/\n/g'
+        local value="${1:-${PATH}}"
+        echo -e "${value//:/\\n}"
     }
 
     # Disable Ctrl-S/Ctrl-Q. The past is not the future.
@@ -728,8 +735,11 @@ fi
 # if the home directory is shared over NFS.
 #
 
-[[ -f ~/.bashrc-local ]] && source ~/.bashrc-local
-[[ -f ~/.bashrc-$HOSTNAME ]] && source ~/.bashrc-$HOSTNAME
+for file in ~/.bashrc-local ~/.bashrc-"${HOSTNAME}"; do
+    if [[ -f "${file}" ]]; then
+        source "${file}"
+    fi
+done
 
 # Force $? to be 0 (for the initial PS1)
 true
